general {
    col.active_border   = rgba(F7DCDE39)
    col.inactive_border = rgba(A58A8D30)
    gaps_in = 2
    gaps_out = 6
    resize_on_border    = true
    layout              = dwindle
}

# ────────────────────────────────────────────────
#  Layout Tweaks & Cursor
# ────────────────────────────────────────────────
dwindle {
    preserve_split        = true
    special_scale_factor  = 0.8
    #smart_split          = true
}

master {
    new_status = master
    new_on_top = 1
    mfact      = 0.5
}

# ────────────────────────────────────────────────
#  Rendering & XWayland
# ────────────────────────────────────────────────
render {
    direct_scanout = 0
}

xwayland {
    enabled              = true
    force_zero_scaling   = true
}

# ────────────────────────────────────────────────
#  Bind Behavior
# ────────────────────────────────────────────────
binds {
    workspace_back_and_forth = true
    allow_workspace_cycles   = true
    pass_mouse_when_bound    = false
}
