# Hecate Dotfiles Configuration

[metadata]
version = "v0.3.8 blind owl"
install_date = "2025-01-01"
last_update = "2025-01-01"
repo_url = "https://github.com/Aelune/Hecate.git"

[preferences]
terminal = "ghostty"
shell = "zsh"
browser = "firefox"
profile = "minimal"

[theme]
# Theme mode: "dynamic" or "static"
# dynamic: Automatically updates system colors when wallpaper changes
# static: Keeps colors unchanged regardless of wallpaper
mode = "dynamic"
