#  _   _ _____ ____    _  _____ _____
# | | | | ____/ ___|  / \|_   _| ____|     /\_/\
# | |_| |  _|| |     / _ \ | | |  _|      ( o.o )
# |  _  | |__| |___ / ___ \| | | |___      > ^ <
# |_| |_|_____\____/_/   \_\_| |_____|

# Wallust Configuration
no_seq = true

[templates]
hyprland = { template = "hyprland.conf", target = "~/.config/hypr/wallust/wallust-hyprland.conf" }
