// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetEnhancedSystemStats():Promise<main.EnhancedSystemStats>;

export function GetEnhancedSystemStatsDebug():Promise<Record<string, any>>;

export function GetGTKColors():Promise<main.GTKColors>;
