// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnhancedSystemStats() {
  return window['go']['main']['App']['GetEnhancedSystemStats']();
}

export function GetEnhancedSystemStatsDebug() {
  return window['go']['main']['App']['GetEnhancedSystemStatsDebug']();
}

export function GetGTKColors() {
  return window['go']['main']['App']['GetGTKColors']();
}
